name: CI/CD

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: kalibre-ebook-convert
    env:
      DJANGO_SETTINGS_MODULE: ebook_convert.settings
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    services:
      db:
        image: postgres:12-alpine
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.11.5
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.5
  
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libpq-dev gcc
  
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install psycopg2-binary
        python -m pip install psycopg2
        python -m pip install coverage
  
    - name: Run tests
      run: coverage run manage.py test